name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Gracias por publicar tu' first issue' Nos alegra tenerte aqui!"
        pr-message: "Gracias por tu' first pull request' Genial que quieras colaborar con nosotros!!"
